### ISSUE TITLE
async and await will be keywords in Python 3.7

### ISSUE THREAD

**Issue by JelleZijlstra** [quora/asynq#20]
Python 3.5 introduced `async` and `await` as context-dependent keywords, and their usage as identifiers is deprecated. In 3.7, they will be full keywords, so usage of these names as e.g. a function name will be a SyntaxError (see https://www.python.org/dev/peps/pep-0492/#deprecation-plans).

`asynq` uses both `async` and `await` as function names. I propose that we rename the functions, but keep the old names as aliases in Python <3.7 for external code to use.

Here are my suggestions for renaming:

- `@async()` can be renamed to `@coroutine()`, by analogy with the `@asyncio.coroutine` decorator of Python 3.4 for `asyncio` coroutines.
- `await()` (which is not useful very often) can be renamed to `await_tasks`.

**Comment by manannayak** [comment]
Both the suggestions sound good to me. Thanks for raising this!
Will try to get to this sometime soon, but feel free to also submit pull requests.

**Comment by snihalani** [comment]
sgtm. 

might be a good time to evaluate if we want to keep this decorator with parenthesis since the asyncio one is without and it'd trip people.

**Comment by LiraNuna** [comment]
Since this sounds like a breaking change, what's the proposed migration path?
Since 3.7 won't come out until 2018-06-15 (see https://www.python.org/dev/peps/pep-0537/), maybe this is better postponed?

**Comment by JelleZijlstra** [comment]
I'm planning to keep the old names around, but add aliases for compatibility. Existing code should continue to work.
