### ISSUE TITLE
Providing pre-built wheels

### ISSUE THREAD

**Issue by kennydo** [quora/asynq#66]
`asynq` has been a fantastic library for us, but having to install `Cython` to compile it slows down our build and complicates artifact building. How feasible is it to provide pre-built wheels of `asynq`?

It looks like https://github.com/scrapinghub/python-crfsuite/pull/53/files is an example of a travis.yml that builds manylinux wheels.

**Comment by JelleZijlstra** [comment]
Yes, this would be useful! Feel free to submit a PR yourself, or else we'll get to it at some point.

**Comment by JelleZijlstra** [comment]
We just released qcore 0.5.0 and asynq 1.1.0 with manylinux wheels.
