### ISSUE TITLE
asynq/qcore is incompatible with six > 1.10.0

### ISSUE THREAD

**Issue by chiconguyen2601** [quora/asynq#68]
Hi Guys,

I have installed asynq with two commands as below on python 2.7.14:
pip install qcore
pip install asynq

It has been installed successfully. But when I try importing the library asynq with line: `from asynq import async `
I encounter the error as following:
`Traceback (most recent call last):
File "app.py", line 13, in 
from asynq import async
File "/usr/local/lib/python2.7/site-packages/asynq/init.py", line 24, in 
from . import debug
File "/usr/local/lib/python2.7/site-packages/asynq/debug.py", line 18, in 
import qcore
File "/usr/local/lib/python2.7/site-packages/qcore/init.py", line 21, in 
from . import events
File "qcore/events.py", line 377, in init qcore.events
File "/usr/local/lib/python2.7/site-packages/six.py", line 831, in prepare
return meta.prepare(name, bases)
AttributeError: type object 'EnumBasedEventHubType' has no attribute 'prepare'`

Could you help me to check why? Thank you very much.

**Comment by JelleZijlstra** [comment]
I think this happens when you use a more recent version of six than 1.10.0. Can you try pinning six to 1.10.0?

On our side, we should fix this by either pinning six to 1.10.0 or fixing the incompatibility in qcore.

**Comment by chiconguyen2601** [comment]
Thank you.
I have installed by python setup.py install. It worked.

P/s: I close this topic now. Thank you again!

**Comment by JelleZijlstra** [comment]
Let's keep this open to track fixing this in asynq/qcore itself.

**Comment by JelleZijlstra** [comment]
quora/qcore#51 fixed this.
